### PR TITLE
Updated Readme with Screen Sketch

### PR DESCRIPTION
**Pull request by plinck**
I had to change the file name of the image since the MD file didnt like a space in the name of it.  I also changed the README.md file to include that image

### CODE REVIEW

**Comment by KHAUNA** [comment]
Git hub works quite well from your phone it seems.  Kind nice.

**Comment by plinck** [comment]
Wow.  Thats cool.  I didn’t even know that.  Nice find!

**Comment by KHAUNA** [comment]
Well it doesn't look like I can approve it from my phone though.  I guess that makes sense if I can actually view the code from here...but still you think they would let me do it on mobile.

**Comment by plinck** [comment]
> Maybe I spoke too soon, it doesn't look like I can approve it from my phone though. I guess that makes sense if I cant actually view the code from here...but still you think they would let me do it on mobile.

Thats a bummer

**Pull request merged**
